### PR TITLE
Generate only one CrossRef article_title and Updates:

### PR DESCRIPTION
**Pull request by michaelstoner**
Using one of: data-title(preferred) or article-title; Use new Crossref_Schematron.zip url; use correct ENV for xmlcatalog

### CODE REVIEW

**Comment by hubgit** [comment]
@michaelstoner Have there been occasions where a citation has both a data-title and an article-title and both are valid? In the past it's usually meant that something's wrong and one of the titles needs to be removed.

**Comment by michaelstoner** [comment]
@hubgit it's a very good point, and something I have considered.  The [spec](https://jats.nlm.nih.gov/archiving/tag-library/1.1/element/data-title.html) indicates that the data-title element is is typically used as an equivalent of an article-title, so that using both is not a typically case. 
This [NISO spec](http://www.niso.org/apps/group_public/download.php/15933/z39_96-2015.pdf) states that data-title:
> The formal title or name of a cited data source (or a component of a cited data source) such as a dataset or spreadsheet.

vesus article-title:
> Full title of an article

I favour handling this case in this way as the spec did not restrict the permissible elements, so allowed both to exist, but for CrossRef exported we need data-title. 

I shall also be trying to ensure that the supplier of the JATS is informed of the above, that using both should not occur.  I have a task to update the validation suite we provide to the supplier so that this case would fail those checks.

**Comment by hubgit** [comment]
Indeed - ideally there would be a schematron test to catch cases in the XML where both a data-title and article-title are provided in the XML (and that they're used appropriately, for data/software vs article citations), as the DTD isn't strict enough to control this. Although the spec allows both to exist, having two titles has (so far) always meant that there's something which needs correcting in the article XML.

**Comment by michaelstoner** [comment]
I'll investigate this one further, I guess the real issue is that it's a DTD based specification which doesn't allow for the more complex restrictions that XSD would have allowed.

**Comment by hubgit** [comment]
Schematron is what publishers usually use to enforce rules that can't be captured by the XML schema, e.g. https://github.com/elifesciences/elife-schematron

**Comment by michaelstoner** [comment]
Ok, I'm going revert these recent changes, and then apply them once I've have confirmation.

**Pull request merged**
